/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/static/gltf_files/2.gltf')
  return (
    <group postion={[10, 10 ,10]} scale={100} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['catan_main_number-tokens014'].geometry} material={nodes['catan_main_number-tokens014'].material} />
    </group>
  )
}

useGLTF.preload('static/gltf_files/2.gltf')
