/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useControls} from 'leva'

export default function Model({ ...props }) {
  const {x, y, z} = useControls({x: {
    value: -32.2,
    step: 0.2,
  }, y: {
    value: -44.4,
    step: 0.2,
  }, z: {
    value: 10,
    step: 0.2,
  }})
  const group = useRef()
  const { nodes, materials } = useGLTF('/static/gltf_files/2.gltf')
  return (
    <group position={[x, y , z]} ref={group} {...props} dispose={null} rotation-x={Math.PI/2} >
      <mesh geometry={nodes['catan_main_number-tokens014'].geometry}>
        <meshStandardMaterial attach="material" color="grey" />
      </mesh>
    </group>
  )
}

useGLTF.preload('static/gltf_files/2.gltf')
