/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useControls} from 'leva'

export default function DesertTile( {position} ) {
  const group = useRef()
  const {x,y,z, rad, height} = useControls({x: {
    value: position[0],
    min: -200,
    max: 200,
    step: .5
  }, y: {
    value: position[1],
    min: -200,
    max: 200,
    step: .5
  }, z: {
    value: position[2],
    min: -200,
    max: 200,
    step: .5
  },
  rad: {
    value: 20,
    min: 0,
    max: 100,
    step: .2
  },
  height: {
    value: 5,
    min: 0,
    max: 100,
    step: .2

  }})
  const { nodes, materials } = useGLTF('../../static/gltf_files/desert.gltf')
  return (
    <group ref={group} position={[position[0]-1,position[1],position[2]+3]} dispose={null} rotation-x={-Math.PI/2}>
      <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material}
      material-color="yellow" />
      <mesh castShadow receiveShadow position={[x,y,z]} rotation-x={-Math.PI/2}>
        <cylinderBufferGeometry attach="geometry" args={[rad,rad, height, 20]}  />
        <meshBasicMaterial attach="material" color="white" />
      </mesh>
    </group>
  )
}

useGLTF.preload('../../static/gltf_files/desert.gltf')
