/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export default function WoodsTile({ position }) {
  const { nodes, materials } = useGLTF("/gltf_files/KatanPiece.gltf");
  const ref = useRef();

  useEffect(() => {
    console.log(ref);
  }, []);

  return (
    <mesh
      rotation={[-Math.PI / 2, 0, 0]}
      ref={ref}
      geometry={nodes.Mesh_Mesh_head_geo001_lambert2SG001.geometry}
      material={materials["lambert2SG.001"]}
      material-wireframe={false}
      position={position}
      material-color="yellow"
    >
      {/* <meshPhysicalMaterial attach="material" color="green" /> */}
    </mesh>
  );
}

useGLTF.preload("/gltf_files/KatanPiece.gltf");
